import localFont from "next/font/local";
import "./globals.css";
import { Rowdies } from "next/font/google";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const rowdiesBold = Rowdies({
  weight: "700",
  subsets: ["latin"]
});


export const metadata = {
  title: "BonAfiyet",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const header = (
    <header>
      <section className="max-w-4xl mx-auto p-4 flex justify-between items-center">
        <Link href="/"><h1 className={`${rowdiesBold.className} text-2xl font-bold text-black`}>BonAfiyet</h1></Link>
        <Link href="/recipe" className="text-xl font-semibold hover:opacity-70">Recipe Page</Link>
      </section>
    </header>
  )

  const footer = (
    <footer className=" mx-24 py-4 mt-8 flex justify-center text-sm text-slate-400">
      Made with 🩷 by Sümeyye Sever
    </footer>
  )


  return (
    <html lang="en">
      <body
        className={`min-h-screen ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {header}
        {children}
        {footer}
      </body>
    </html>
  );
}
